### ISSUE TITLE
KafkaWordCount gives runtime error 

### ISSUE THREAD

**Issue by DeanSha** [cotdp/spark-example-kafka#1]
Per your instructions I created the kafka topic "wordcount" and populated it with messages. I had to do it manually as your producer also gave  runtime error. But the main issue was the spark streaming program.
sbt assembly worked fine.
But running KafkaWordCount gave the following errors. 

Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.streaming.StreamingContext$.toPairDStreamFunctions(Lorg/apache/spark/streaming/dstream/DStream;Lscala/reflect/ClassTag;Lscala/reflect/ClassTag;Lscala/math/Ordering;)Lorg/apache/spark/streaming/dstream/PairDStreamFunctions;
	at spark.example.kafka.KafkaWordCount$.main(KafkaWordCount.scala:61)
	at spark.example.kafka.KafkaWordCount.main(KafkaWordCount.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:755)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
17/10/01 18:01:05 INFO SparkContext: Invoking stop() from shutdown hook

**Comment by DeanSha** [comment]
Here's the complete log if it helps:
$ bin/KafkaWordCount localhost:2181 KafkaWordCount wordcount 1
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
17/10/01 18:01:03 INFO SparkContext: Running Spark version 2.2.0
17/10/01 18:01:03 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
17/10/01 18:01:03 INFO SparkContext: Submitted application: KafkaWordCount
17/10/01 18:01:03 INFO SecurityManager: Changing view acls to: deansha
17/10/01 18:01:03 INFO SecurityManager: Changing modify acls to: deansha
17/10/01 18:01:03 INFO SecurityManager: Changing view acls groups to: 
17/10/01 18:01:03 INFO SecurityManager: Changing modify acls groups to: 
17/10/01 18:01:03 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(deansha); groups with view permissions: Set(); users  with modify permissions: Set(deansha); groups with modify permissions: Set()
17/10/01 18:01:04 INFO Utils: Successfully started service 'sparkDriver' on port 52140.
17/10/01 18:01:04 INFO SparkEnv: Registering MapOutputTracker
17/10/01 18:01:04 INFO SparkEnv: Registering BlockManagerMaster
17/10/01 18:01:04 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
17/10/01 18:01:04 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
17/10/01 18:01:04 INFO DiskBlockManager: Created local directory at /private/var/folders/ks/42zkb3px6651hyyccsb7cxs40000gn/T/blockmgr-84420616-4174-4471-96b0-dcef943ff268
17/10/01 18:01:04 INFO MemoryStore: MemoryStore started with capacity 366.3 MB
17/10/01 18:01:04 INFO SparkEnv: Registering OutputCommitCoordinator
17/10/01 18:01:04 INFO Utils: Successfully started service 'SparkUI' on port 4040.
17/10/01 18:01:04 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://192.168.1.111:4040
17/10/01 18:01:04 INFO SparkContext: Added JAR file:y/KTest1/spark-example-kafka/target/scala-2.10/spark-example-kafka_2.10-1.0.jar at spark://192.168.1.111:52140/jars/spark-example-kafka_2.10-1.0.jar with timestamp 1506906064541
17/10/01 18:01:04 INFO Executor: Starting executor ID driver on host localhost
17/10/01 18:01:04 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 52141.
17/10/01 18:01:04 INFO NettyBlockTransferService: Server created on 192.168.1.111:52141
17/10/01 18:01:04 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
17/10/01 18:01:04 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 192.168.1.111, 52141, None)
17/10/01 18:01:04 INFO BlockManagerMasterEndpoint: Registering block manager 192.168.1.111:52141 with 366.3 MB RAM, BlockManagerId(driver, 192.168.1.111, 52141, None)
17/10/01 18:01:04 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 192.168.1.111, 52141, None)
17/10/01 18:01:04 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 192.168.1.111, 52141, None)
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.streaming.StreamingContext$.toPairDStreamFunctions(Lorg/apache/spark/streaming/dstream/DStream;Lscala/reflect/ClassTag;Lscala/reflect/ClassTag;Lscala/math/Ordering;)Lorg/apache/spark/streaming/dstream/PairDStreamFunctions;
	at spark.example.kafka.KafkaWordCount$.main(KafkaWordCount.scala:61)
	at spark.example.kafka.KafkaWordCount.main(KafkaWordCount.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:755)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
17/10/01 18:01:05 INFO SparkContext: Invoking stop() from shutdown hook
17/10/01 18:01:05 INFO SparkUI: Stopped Spark web UI at http://192.168.1.111:4040
17/10/01 18:01:05 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
17/10/01 18:01:05 INFO MemoryStore: MemoryStore cleared
17/10/01 18:01:05 INFO BlockManager: BlockManager stopped
17/10/01 18:01:05 INFO BlockManagerMaster: BlockManagerMaster stopped
17/10/01 18:01:05 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
17/10/01 18:01:05 INFO SparkContext: Successfully stopped SparkContext
17/10/01 18:01:05 INFO ShutdownHookManager: Shutdown hook called
17/10/01 18:01:05 INFO ShutdownHookManager: Deleting directory /private/var/folders/ks/42zkb3px6651hyyccsb7cxs40000gn/T/spark-d8bff290-811a-47d2-af04-df276a40ee1a
